### ISSUE TITLE
failure at second level when called with --local-threads 1

### ISSUE THREAD

**Issue by steelec** [CoBrALab/twolevel_ants_dbm#9] opened 2019-04-29 15:58 UTC
The call: 
```sh
twolevel_ants_dbm/twolevel_dbm.py --cluster-type local --local-threads 1 -i UNI_T1/2019_04_d01256_UNI_img_for_twolevel_DBM.csv 2level
```

fails at: 
```
Processing Second-Level DBM outputs
  0%|                                                                    | 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "twolevel_ants_dbm/twolevel_dbm.py", line 520, in <module>
    main()
  File "twolevel_ants_dbm/twolevel_dbm.py", line 514, in main
    firstlevel(inputs, args)
  File "twolevel_ants_dbm/twolevel_dbm.py", line 167, in firstlevel
    secondlevel(imagelist, args, secondlevel=True)
  File "twolevel_ants_dbm/twolevel_dbm.py", line 233, in secondlevel
    pool.map(lambda x: run_command(x, args.dry_run), commands)
  File "/opt/quarantine/anaconda3/2018.12/install/lib/python3.7/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/opt/quarantine/anaconda3/2018.12/install/lib/python3.7/site-packages/multiprocess/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/quarantine/anaconda3/2018.12/install/lib/python3.7/site-packages/multiprocess/pool.py", line 381, in _map_async
    raise ValueError("Pool not running")
ValueError: Pool not running
```

**Comment by gdevenyi** [comment] 2019-04-29 16:03
CSV please.

**Comment by steelec** [comment] 2019-04-29 16:29
renamed as .txt for upload
[2019_04_d01256_UNI_img_for_twolevel_DBM.txt](https://github.com/CobraLab/twolevel_ants_dbm/files/3128282/2019_04_d01256_UNI_img_for_twolevel_DBM.txt)

**Comment by steelec** [comment] 2019-05-02 15:06
works when the following is set: --local-threads 2
I will look into it

**Comment by gdevenyi** [comment] 2019-05-02 15:32
Okay, thats helpful thanks.

I'm going to break out the parallelism for the model builds vs the parallelism for the post-processing.

**Comment by steelec** [comment] 2019-05-02 15:37
likely this issue: https://github.com/uqfoundation/pathos/issues/111
issue reproducible by running the following code, uncommenting pool.restart() fixes the issue.

Shall I go ahead and add a pool.restart() after the close calls? (there are 2)

```python
import subprocess
import sys

import pathos.multiprocessing as multiprocessing  # Better multiprocessing

def run_command(command, verbose=True):
    dryrun=False
    if dryrun:
        print(command)
        fakereturn = subprocess.CompletedProcess
        fakereturn.stdout = "".encode()
        return (fakereturn)
    else:
        if verbose:
            print(f"twolevel_dbm.py: running command {command}")
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=True,
            shell=True)
        return (result)

pool = multiprocessing.ProcessPool(nodes=1)
pool.map(lambda x: run_command(x), ['ls','ls -al'])
pool.close()
#pool.restart()
pool = multiprocessing.ProcessPool(nodes=1)
pool.map(lambda x: run_command(x), ['ls','ls -al'])
```

**Comment by gdevenyi** [comment] 2019-05-02 15:51
Okay, so the issue is that at level 1 I create a pool and use it "pool" and then I close it when done.

At level 2, I then re-use the name pool and I think I'm creating a new pool, but the linked bug indicates that a new pool doesn't get created because I'm calling with the same configuration as before.

My preferred fix going forward is to rename the second pool instance, so that there can't be this crosstalk, as I'm going to split up the threading at level 1 and level 2.

As a short-term fix, a restart at level2 after the pool = should fix the immediate bug.

**Comment by gdevenyi** [comment] 2019-05-02 15:53
There's no need for a restart at the second close, since pool is never used again, and the restart should happen after pool init, not after close.

I'm disappointed that this is buggy like this. This amounts to "hidden state" which is a big design flaw for using code.

**Comment by gdevenyi** [comment] 2019-05-02 15:56
It looks like a more sensible solution is to call pool.clear() to completely destroy the pool so that a new instance is created at the second level.

I'll push a patch

**Comment by steelec** [comment] 2019-05-02 15:57
ah, k. will kill my pull request

**Closed as completed** 2019-05-02 16:12 UTC
